# frozen_string_literal: true

# Authoring-time font subsetter (NOT part of the gate; the gate only
# verifies coverage via the committed manifests). For every script in
# ScriptScan::SCRIPTS, scans site/ for that script's codepoints and
# subsets the vendored full Noto face down to exactly the glyphs in
# use, so pages stay light. Scripts with no codepoints in site/ are
# skipped (no subset, no manifest — the gate then has nothing to
# check for them). Requires harfbuzz's hb-subset (brew install
# harfbuzz).
#
# Usage: ruby script/subset_fonts.rb   (or: rake fonts)

require "fileutils"
require_relative "script_scan"

SOURCE_OFL = "assets-src/fonts/OFL.txt"
OUT_DIR = "site/assets/fonts"

abort "subset: hb-subset not found (brew install harfbuzz)" if `which hb-subset`.empty?

FileUtils.mkdir_p(OUT_DIR)
subsetted = 0

Edubba::ScriptScan::SCRIPTS.each do |name, script|
  used = Edubba::ScriptScan.used_codepoints("site", script[:range]).sort
  if used.empty?
    puts "subset: #{name} — no codepoints in site/, skipped"
    next
  end
  abort "subset: #{script[:source_ttf]} missing" unless File.exist?(script[:source_ttf])

  unicodes = used.map { |cp| Edubba::ScriptScan.format_codepoint(cp) }.join(",")
  ok = system("hb-subset", script[:source_ttf],
              "--unicodes=#{unicodes}",
              "--output-file=#{script[:subset_ttf]}")
  abort "subset: hb-subset failed for #{name}" unless ok

  File.write(script[:manifest], <<~HEADER + used.map { |cp| Edubba::ScriptScan.format_codepoint(cp) }.join("\n") + "\n")
    # Codepoints covered by #{File.basename(script[:subset_ttf])} (hex,
    # one per line). Generated by script/subset_fonts.rb — do not edit
    # by hand; the gate fails if site/ uses a #{name} codepoint not
    # listed here.
  HEADER
  puts "subset: #{name} — #{used.size} codepoints -> #{script[:subset_ttf]} (#{File.size(script[:subset_ttf])} bytes)"
  subsetted += 1
end

FileUtils.cp(SOURCE_OFL, File.join(OUT_DIR, "OFL.txt")) if subsetted.positive?
