# frozen_string_literal: true

# Authoring-time font subsetter (NOT part of the gate; the gate only
# verifies coverage via the committed manifest). Scans site/ for
# cuneiform codepoints and subsets the vendored full Noto Sans
# Cuneiform down to exactly the glyphs in use, so pages stay light.
# Requires harfbuzz's hb-subset (brew install harfbuzz).
#
# Usage: ruby script/subset_fonts.rb   (or: rake fonts)

require "set"
require_relative "cuneiform_scan"

SOURCE_TTF = "assets-src/fonts/NotoSansCuneiform-Regular.ttf"
SOURCE_OFL = "assets-src/fonts/OFL.txt"
OUT_DIR = "site/assets/fonts"
OUT_TTF = File.join(OUT_DIR, "NotoSansCuneiform-subset.ttf")

abort "subset: #{SOURCE_TTF} missing" unless File.exist?(SOURCE_TTF)
abort "subset: hb-subset not found (brew install harfbuzz)" if `which hb-subset`.empty?

used = Edubba::CuneiformScan.used_codepoints("site").sort
abort "subset: no cuneiform codepoints found in site/ — nothing to do" if used.empty?

require "fileutils"
FileUtils.mkdir_p(OUT_DIR)

unicodes = used.map { |cp| Edubba::CuneiformScan.format_codepoint(cp) }.join(",")
ok = system("hb-subset", SOURCE_TTF,
            "--unicodes=#{unicodes}",
            "--output-file=#{OUT_TTF}")
abort "subset: hb-subset failed" unless ok

File.write(File.join(OUT_DIR, "cuneiform-coverage.txt"), <<~HEADER + used.map { |cp| Edubba::CuneiformScan.format_codepoint(cp) }.join("\n") + "\n")
  # Codepoints covered by NotoSansCuneiform-subset.ttf (hex, one per
  # line). Generated by script/subset_fonts.rb — do not edit by hand;
  # the gate fails if site/ uses a cuneiform codepoint not listed here.
HEADER
FileUtils.cp(SOURCE_OFL, File.join(OUT_DIR, "OFL.txt"))

puts "subset: #{used.size} codepoints -> #{OUT_TTF} (#{File.size(OUT_TTF)} bytes)"
